name = "MicMods"
uuid = "501e2f80-3d20-4466-9742-a3793080ee5c"
authors = ["Thomas Wutzler <progtw@arcor.de> and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
DifferentialEquations = "6.16"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
